### ISSUE TITLE
Add https support

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [jadengore/Ingredients#12]
This should be added so that development is more similar to the deployment environment. It will support continuous deployment later down the road. Oh and security.
- Set up Heroku
- ~~Get https certificates~~
- Set up https

**Comment by ebramanti** [comment]
Already have the certificates bought. Let's talk more about our deployment options. I'm willing to give Heroku another try, especially since its much easier to do with our current back end.

**Comment by AuthorOfTheSurf** [comment]
I am on-board with Heroku, maybe we could still have a separate db server, ideally one that's free. Db-setup can be a pain there, and we should really just use it for staging as it does make that a breeze.

edit: heroku is np with https support right?

**Comment by ebramanti** [comment]
@AuthorOfTheSurf Yes, still haven't gotten to this.
